---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "arcgis-web-appbuilder.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "arcgis-web-appbuilder.name" . }}
    helm.sh/chart: {{ include "arcgis-web-appbuilder.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "arcgis-web-appbuilder.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
...
